import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from './components/Header';
import Footer from './components/Footer';

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps>=({children})=> {
  return (
    <html>
      <body>
    <div className="container">
      <head>
        <title>Quiz App</title>
        <meta name="description" content="Quiz App"/>
      </head>
      <Header/>
      <main className="main">{children}</main>
      <Footer/>
    </div>
    </body>
    </html>
  );
};

export default Layout;

/*const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
*/